# .bashrc

if ! [ -f /run/user/$UID/runonce_set_custom_env ]; then
    touch /run/user/$UID/runonce_set_custom_env
    if command -v zoxide >/dev/null 2>&1; then
        ZOXIDE_IS_INSTALLED=true
    else
        ZOXIDE_IS_INSTALLED=false
    fi
    export ZOXIDE_IS_INSTALLED

    if command -v starship >/dev/null 2>&1; then
        STARSHIP_IS_INSTALLED=true
    else
        STARSHIP_IS_INSTALLED=false
    fi
    export STARSHIP_IS_INSTALLED

    if command -v keychain >/dev/null 2>&1; then
        KEYCHAIN_IS_INSTALLED=true
    else
        KEYCHAIN_IS_INSTALLED=false
    fi
    export KEYCHAIN_IS_INSTALLED

    if command -v eza >/dev/null 2>&1; then
        EZA_IS_INSTALLED=true
    else
        EZA_IS_INSTALLED=false
    fi
    export EZA_IS_INSTALLED

    if command -v fzf >/dev/null 2>&1; then
        FZF_IS_INSTALLED=true
    else
        FZF_IS_INSTALLED=false
    fi
    export FZF_IS_INSTALLED
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if [ -f ~/.bash_git ]; then
  . ~/.bash_git
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/.go/bin:$PATH"
PATH="$HOME/.dotnet/tools/:$PATH"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

export PS1="\[╭─ \w\n╰\[\033[0;34m\]\u\[\033[0m\]@\h \[\033[0;34m\]->>\[\033[0m\] "

export EDITOR=/usr/bin/nvim
export TERMINAL=/usr/bin/foot
export OPENSSL_DIR=/etc/pki/tls
export OPENSSL_LIB_DIR=/usr/lib64
export OPENSSL_INCLUDE_DIR=/usr/include/openssl
export GRIM_DEFAULT_DIR=$(xdg-user-dir PICTURES)/Screenshots/
export GOPATH=$HOME/.go/
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT="%Y-%m-%d %r %t"

if $KEYCHAIN_IS_INSTALLED; then
  eval `keychain -q --eval gh_key gl_key`
fi

if $STARSHIP_IS_INSTALLED; then
  eval "$(starship init bash)"
fi

if $FZF_IS_INSTALLED; then
  eval "$(fzf --bash)"
fi

if $ZOXIDE_IS_INSTALLED; then
  eval "$(zoxide init --cmd cd bash)"
fi

PROMPT_COMMAND='printf "\e]7;file://%s%s\a" "$HOSTNAME" "$PWD"; '"$PROMPT_COMMAND"

set -o vi
bind -m vi-insert "\\C-L":clear-screen
