format = """
╭─ $directory $git_branch $cpp$c$python$lua$rust$nodejs
╰$username@$hostname $character"""

add_newline = false

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = "󱘗 "
format = "[$symbol($version )]($style)"

[cpp]
symbol = " "
format = "[$symbol($version )]($style)"
disabled = false

[c]
symbol = " "
format = "[$symbol($version )]($style)"

[username]
show_always = true
format = "[$user](blue)"

[hostname]
ssh_symbol = " "
ssh_only = false
format = "[$ssh_symbol$hostname](white)"

[directory]
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($read_only_style)"
style = "white"
use_logical_path = false
truncate_to_repo = false

[character]
format = "[->>](blue) "

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch)](bold cyan) "
