[opener]
open = [
  { run = "xdg-open %s1", desc = "Open", spread = true },
]

edit = [
  { run = "$EDITOR %s", desc = "Edit", block = true, for = "unix" },
]

play = [
	{ run = "mpv %s", desc = "Play" },
]

[plugin]
prepend_previewers = [
  { mime = "video/*", run = "video" },
]
