# Key Bindings

# reload config
bind=SUPER+SHIFT,R,reload_config

# toggle overview
bind=SUPER,O,toggleoverview

# app binds
bind=SUPER,D,spawn,noctalia msg panel-toggle launcher
bind=SUPER,T,spawn,wezterm
bind=SUPER,B,spawn,gtk-launch com.brave.Origin.desktop
bind=super,E,spawn,wezterm -e yazi
bind=CTRL+SHIFT,Caps_Lock,spawn,wezterm -e btop

# noctalia binds
bind=SUPER,Space,spawn,noctalia msg panel-toggle control-center home
bind=SUPER,C,spawn,noctalia msg panel-toggle clipboard
bind=SUPER+ALT,C,spawn,noctalia msg clipboard-clear
bind=SUPER,N,spawn,noctalia msg panel-toggle control-center notifications
bind=SUPER+SHIFT,N,spawn,noctalia msg notification-clear-history
bind=SUPER+ALT,N,spawn,noctalia msg notification-dnd-toggle
bind=CTRL+ALT,Q,spawn,loginctl lock-session
bind=CTRL+ALT,E,spawn,noctalia msg panel-toggle session
bind=CTRL+ALT,S,spawn,noctalia msg settings-toggle
bind=CTRL+ALT,D,spawn,~/.config/mango/scripts/dim.sh

# exit
bind=CTRL+ALT,Delete,quit
bind=SUPER,Q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER+SHIFT,Tab,focusstack,previous
bind=SUPER,H,focusdir,left
bind=SUPER,J,viewtoright,0
bind=SUPER,K,viewtoleft,0
bind=SUPER,L,focusdir,right

# swap window
bind=SUPER+SHIFT,H,exchange_client,left
bind=SUPER+SHIFT,J,tagtoright,down
bind=SUPER+SHIFT,K,tagtoleft,up
bind=SUPER+SHIFT,L,exchange_client,right

# scroller layout
bind=SUPER,F,switch_proportion_preset,

# Move to tag
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# Move window to tag and focus
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Move window to tag
bind=SUPER+CTRL,1,tagsilent,1,0
bind=SUPER+CTRL,2,tagsilent,2,0
bind=SUPER+CTRL,3,tagsilent,3,0
bind=SUPER+CTRL,4,tagsilent,4,0
bind=SUPER+CTRL,5,tagsilent,5,0
bind=SUPER+CTRL,6,tagsilent,6,0
bind=SUPER+CTRL,7,tagsilent,7,0
bind=SUPER+CTRL,8,tagsilent,8,0
bind=SUPER+CTRL,9,tagsilent,9,0

# Resize floating window
bind=SUPER,Equal,resizewin,+50,+0
bind=SUPER,Minus,resizewin,-50,+0
bind=SUPER+SHIFT,Equal,resizewin,+0,+50
bind=SUPER+SHIFT,Minus,resizewin,+0,-50

# Move floating window
bind=SUPER+CTRL,H,movewin,-50,+0
bind=SUPER+CTRL,J,movewin,+0,+50
bind=SUPER+CTRL,K,movewin,+0,-50
bind=SUPER+CTRL,L,movewin,+50,+0

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Media
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=NONE,XF86AudioMicMute,spawn,noctalia msg mic-mute
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down
bind=NONE,XF86Display,spawn,wl-mirror eDP-1
bind=NONE,XF86Keyboard,spawn,gnome-calculator

# Toggle floating window state
bind=SUPER,v,togglefloating

# Screenshot
bind=NONE,Print,spawn,noctalia msg screenshot-region
bind=CTRL,Print,spawn,noctalia msg screenshot-fullscreen

# Lid close event
switchbind=fold,spawn,noctalia msg session lock-and-suspend
