# reload config
bind=Super+Shift,r,spawn_shell,bash ~/.config/mango/scripts/config_check.sh
bind=Super+Shift,r,reload_config

# menu and terminal
bind=Super,T,spawn,foot
bind=Super,D,spawn,fuzzel
bind=Super+Shift,D,spawn,nwggrid

# exit ctrl+alt+delete
bind=Ctrl+Alt,Delete,quit
bind=Super,Q,killclient,

# switch window focus
bind=Alt,Tab,focusstack,next
bind=Super,U,focuslast

bind=Super,H,focusdir,left
bind=Super,L,focusdir,right

# swap window
bind=Super+Shift,H,exchange_client,left
bind=Super+Shift,L,exchange_client,right

# movewin
bind=Super+Ctrl,H,movewin,-50,+0
bind=Super+Ctrl,J,movewin,+0,+50
bind=Super+Ctrl,K,movewin,+0,-50
bind=Super+Ctrl,L,movewin,+50,+0


# resizewin
bind=Super,Minus,resizewin,-50,+0
bind=Super,Equal,resizewin,+50,+0
bind=Super+Shift,Minus,resizewin,+0,-50
bind=Super+Shift,Equal,resizewin,+0,+50

# switch window status
bind=Super,O,toggleoverview,0
bind=Super,Space,togglefloating,
bind=Super,F,togglemaximizescreen,
bind=Super+Shift,F,togglefullscreen,

# scroller layout
bind=Super,0,set_proportion,0.5
bind=Super,R,switch_proportion_preset,

# tag switch
bind=Super,J,spawn,~/.config/mango/scripts/handlefocus.sh down
bind=Super,K,spawn,~/.config/mango/scripts/handlefocus.sh up
bind=Super+Shift,J,tagtoright,0
bind=Super+Shift,K,tagtoleft,0

bind=Super,1,view,1,0
bind=Super,2,view,2,0
bind=Super,3,view,3,0
bind=Super,4,view,4,0
bind=Super,5,view,5,0
bind=Super,6,view,6,0
bind=Super,7,view,7,0
bind=Super,8,view,8,0
bind=Super,9,view,9,0

bind=Super+Shift,1,tag,1,0
bind=Super+Shift,2,tag,2,0
bind=Super+Shift,3,tag,3,0
bind=Super+Shift,4,tag,4,0
bind=Super+Shift,5,tag,5,0
bind=Super+Shift,6,tag,6,0
bind=Super+Shift,7,tag,7,0
bind=Super+Shift,8,tag,8,0
bind=Super+Shift,9,tag,9,0

# monitor switch
bind=Super+Ctrl+Shift,H,tagmon,left
bind=Super+Ctrl+Shift,J,tagmon,down
bind=Super+Ctrl+Shift,K,tagmon,up
bind=Super+Ctrl+Shift,L,tagmon,right


# Mouse Button Bindings
mousebind=Super,btn_left,moveresize,curmove
mousebind=Super,btn_right,moveresize,curresize
mousebind=Super+Shift,btn_right,killclient
mousebind=Super+Shift,btn_middle,togglefullscreen

# Gesturebind
gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right
gesturebind=none,up,3,focusdir,up;;
gesturebind=none,down,3,focusdir,down;
gesturebind=none,left,4,viewtoleft_have_client
gesturebind=none,right,4,viewtoright_have_client
gesturebind=none,up,4,toggleoverview,1
gesturebind=none,down,4,toggleoverview,1

# brightness and volume
bind=none,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume.sh up
bind=none,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume.sh down
bind=none,XF86MonBrightnessUp,spawn,~/.config/mango/scripts/brightness.sh up
bind=none,XF86MonBrightnessDown,spawn,~/.config/mango/scripts/brightness.sh down
bind=none,XF86Display,spawn,wl-mirror eDP-1
bind=none,XF86Keyboard,spawn,gnome-calculator

#custom app bind
bind=Super,E,spawn,foot -e yazi
bind=Super+Shift,W,spawn,bash ~/.config/mango/scripts/hide_waybar_mango.sh
bind=Ctrl+Alt,Q,spawn,gtklock
bind=Ctrl+Alt,E,spawn,wlogout -l ~/.config/mango/wlogout
bind=Ctrl+Shift,Caps_Lock,spawn,foot -e btop
bind=Super,N,spawn,swaync-client -t
bind=Super,p,spawn,bash ~/.config/mango/scripts/monitor.sh
bind=Super,B,spawn,flatpak run com.brave.Browser --disable-features=GlobalShortcutsPortal
