# More option see https://github.com/DreamMaoMao/mango/wiki/

exec-once=~/.config/mango/autostart.sh

source=~/.config/mango/binds.conf
source=~/.config/mango/input.conf
source=~/.config/mango/output.conf
source=~/.config/mango/misc.conf
source=~/.config/mango/layout.conf
source=~/.config/mango/rules.conf

source=~/.config/mango/noctalia.conf
