# Scroller Layout Setting
scroller_structs=0
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=0.5
scroller_proportion_preset=0.5,1.0

# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=1
overviewgappi=5
overviewgappo=30

# Appearance
gappih=8
gappiv=8
gappoh=8
gappov=16
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=3

# layout support:
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
